### ISSUE TITLE
Converting SVG to PNG adds white background instead of transparent

### ISSUE THREAD

**Issue by donatasben** [ConvertAPI/convertapi-php#49] opened 2024-02-15 06:46 UTC
When converting an SVG file with transparent background it looses transparency and is added a white background in a PNG output.

Input (has transparency):
![SCR-20240215-idwe](https://github.com/ConvertAPI/convertapi-php/assets/4421344/598d6891-5b54-4462-baf4-f7c057d73d6c)

Output (no more transparency, bad):
![SCR-20240215-idyz](https://github.com/ConvertAPI/convertapi-php/assets/4421344/7ea6ea6c-4d2c-447e-91c4-622066038f25)

**Comment by tomasr78** [comment] 2024-02-19 09:05
This issue is not related to the library. Our developer is working on a fix. I am closing this issue now.

**Closed by tomasr78** 2024-02-19 09:05 UTC

**Comment by tomasr78** [comment] 2024-03-24 15:47
The issue is fixed and will be published in the next release at the end of April.
